spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-fresher
    username: root
    password: 250104
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mySql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true